/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ApiKeyApi,
  BalanceApi,
  BankApi,
  BankAccountApi,
  CurrencyApi,
  MerchantsApi,
  MockPaymentApi,
  PaymentApi,
  RatesApi,
  TransactionApi,
  TransactionsApi,
  VoucherApi,
  VoucherFeeApi,
  VoucherMinMaxAmountApi,
  WalletApi,
  WebhookApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PartnaCustom } from "./client-custom";

export class Partna extends PartnaCustom {
  readonly apiKey: ApiKeyApi;
  readonly balance: BalanceApi;
  readonly bank: BankApi;
  readonly bankAccount: BankAccountApi;
  readonly currency: CurrencyApi;
  readonly merchants: MerchantsApi;
  readonly mockPayment: MockPaymentApi;
  readonly payment: PaymentApi;
  readonly rates: RatesApi;
  readonly transaction: TransactionApi;
  readonly transactions: TransactionsApi;
  readonly voucher: VoucherApi;
  readonly voucherFee: VoucherFeeApi;
  readonly voucherMinMaxAmount: VoucherMinMaxAmountApi;
  readonly wallet: WalletApi;
  readonly webhook: WebhookApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.apiKey = new ApiKeyApi(configuration);
    this.balance = new BalanceApi(configuration);
    this.bank = new BankApi(configuration);
    this.bankAccount = new BankAccountApi(configuration);
    this.currency = new CurrencyApi(configuration);
    this.merchants = new MerchantsApi(configuration);
    this.mockPayment = new MockPaymentApi(configuration);
    this.payment = new PaymentApi(configuration);
    this.rates = new RatesApi(configuration);
    this.transaction = new TransactionApi(configuration);
    this.transactions = new TransactionsApi(configuration);
    this.voucher = new VoucherApi(configuration);
    this.voucherFee = new VoucherFeeApi(configuration);
    this.voucherMinMaxAmount = new VoucherMinMaxAmountApi(configuration);
    this.wallet = new WalletApi(configuration);
    this.webhook = new WebhookApi(configuration);
  }

}
