/* tslint:disable */
/* eslint-disable */
/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CurrencyGetMinimumAllowedResponse } from '../models';
// @ts-ignore
import { CurrencyListSupportedCurrenciesResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CurrencyApi - axios parameter creator
 * @export
 */
export const CurrencyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get minimum amount allowed
         * @summary Get minimum amount allowed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMinimumAllowed: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/currency/minimum-allowed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/currency/minimum-allowed',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get supported currencies
         * @summary Get supported currencies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSupportedCurrencies: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/currency/supported`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/currency/supported',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CurrencyApi - functional programming interface
 * @export
 */
export const CurrencyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CurrencyApiAxiosParamCreator(configuration)
    return {
        /**
         * Get minimum amount allowed
         * @summary Get minimum amount allowed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMinimumAllowed(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyGetMinimumAllowedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMinimumAllowed(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get supported currencies
         * @summary Get supported currencies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSupportedCurrencies(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyListSupportedCurrenciesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSupportedCurrencies(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CurrencyApi - factory interface
 * @export
 */
export const CurrencyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CurrencyApiFp(configuration)
    return {
        /**
         * Get minimum amount allowed
         * @summary Get minimum amount allowed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMinimumAllowed(options?: AxiosRequestConfig): AxiosPromise<CurrencyGetMinimumAllowedResponse> {
            return localVarFp.getMinimumAllowed(options).then((request) => request(axios, basePath));
        },
        /**
         * Get supported currencies
         * @summary Get supported currencies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSupportedCurrencies(options?: AxiosRequestConfig): AxiosPromise<CurrencyListSupportedCurrenciesResponse> {
            return localVarFp.listSupportedCurrencies(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CurrencyApiGenerated - object-oriented interface
 * @export
 * @class CurrencyApiGenerated
 * @extends {BaseAPI}
 */
export class CurrencyApiGenerated extends BaseAPI {
    /**
     * Get minimum amount allowed
     * @summary Get minimum amount allowed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyApiGenerated
     */
    public getMinimumAllowed(options?: AxiosRequestConfig) {
        return CurrencyApiFp(this.configuration).getMinimumAllowed(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get supported currencies
     * @summary Get supported currencies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrencyApiGenerated
     */
    public listSupportedCurrencies(options?: AxiosRequestConfig) {
        return CurrencyApiFp(this.configuration).listSupportedCurrencies(options).then((request) => request(this.axios, this.basePath));
    }
}
