/* tslint:disable */
/* eslint-disable */
/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { MockPaymentRequestSubmission400Response } from '../models';
// @ts-ignore
import { MockPaymentRequestSubmissionRequest } from '../models';
// @ts-ignore
import { MockPaymentRequestSubmissionResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * MockPaymentApi - axios parameter creator
 * @export
 */
export const MockPaymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Sends a mock payment request (only in staging environment)
         * @summary Make a mock payment
         * @param {MockPaymentRequestSubmissionRequest} mockPaymentRequestSubmissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestSubmission: async (mockPaymentRequestSubmissionRequest: MockPaymentRequestSubmissionRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'mockPaymentRequestSubmissionRequest' is not null or undefined
            assertParamExists('requestSubmission', 'mockPaymentRequestSubmissionRequest', mockPaymentRequestSubmissionRequest)
            const localVarPath = `/v1/mock/payment`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: mockPaymentRequestSubmissionRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/mock/payment',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(mockPaymentRequestSubmissionRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MockPaymentApi - functional programming interface
 * @export
 */
export const MockPaymentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MockPaymentApiAxiosParamCreator(configuration)
    return {
        /**
         * Sends a mock payment request (only in staging environment)
         * @summary Make a mock payment
         * @param {MockPaymentApiRequestSubmissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestSubmission(requestParameters: MockPaymentApiRequestSubmissionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MockPaymentRequestSubmissionResponse>> {
            const mockPaymentRequestSubmissionRequest: MockPaymentRequestSubmissionRequest = {
                amount: requestParameters.amount,
                voucherId: requestParameters.voucherId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestSubmission(mockPaymentRequestSubmissionRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MockPaymentApi - factory interface
 * @export
 */
export const MockPaymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MockPaymentApiFp(configuration)
    return {
        /**
         * Sends a mock payment request (only in staging environment)
         * @summary Make a mock payment
         * @param {MockPaymentApiRequestSubmissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestSubmission(requestParameters: MockPaymentApiRequestSubmissionRequest, options?: AxiosRequestConfig): AxiosPromise<MockPaymentRequestSubmissionResponse> {
            return localVarFp.requestSubmission(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for requestSubmission operation in MockPaymentApi.
 * @export
 * @interface MockPaymentApiRequestSubmissionRequest
 */
export type MockPaymentApiRequestSubmissionRequest = {
    
} & MockPaymentRequestSubmissionRequest

/**
 * MockPaymentApiGenerated - object-oriented interface
 * @export
 * @class MockPaymentApiGenerated
 * @extends {BaseAPI}
 */
export class MockPaymentApiGenerated extends BaseAPI {
    /**
     * Sends a mock payment request (only in staging environment)
     * @summary Make a mock payment
     * @param {MockPaymentApiRequestSubmissionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MockPaymentApiGenerated
     */
    public requestSubmission(requestParameters: MockPaymentApiRequestSubmissionRequest, options?: AxiosRequestConfig) {
        return MockPaymentApiFp(this.configuration).requestSubmission(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
