/* tslint:disable */
/* eslint-disable */
/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { RatesGetConversionRatesResponse } from '../models';
// @ts-ignore
import { RatesGetCurrentRatesResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * RatesApi - axios parameter creator
 * @export
 */
export const RatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves conversion rates for all supported currencies
         * @summary Retrieves conversion rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConversionRates: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/currency/rates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/currency/rates',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current rates
         * @summary Get current rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentRates: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/currency/rate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/currency/rate',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RatesApi - functional programming interface
 * @export
 */
export const RatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RatesApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves conversion rates for all supported currencies
         * @summary Retrieves conversion rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConversionRates(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RatesGetConversionRatesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConversionRates(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get the current rates
         * @summary Get current rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentRates(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RatesGetCurrentRatesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentRates(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RatesApi - factory interface
 * @export
 */
export const RatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RatesApiFp(configuration)
    return {
        /**
         * Retrieves conversion rates for all supported currencies
         * @summary Retrieves conversion rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConversionRates(options?: AxiosRequestConfig): AxiosPromise<RatesGetConversionRatesResponse> {
            return localVarFp.getConversionRates(options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current rates
         * @summary Get current rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentRates(options?: AxiosRequestConfig): AxiosPromise<RatesGetCurrentRatesResponse> {
            return localVarFp.getCurrentRates(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RatesApiGenerated - object-oriented interface
 * @export
 * @class RatesApiGenerated
 * @extends {BaseAPI}
 */
export class RatesApiGenerated extends BaseAPI {
    /**
     * Retrieves conversion rates for all supported currencies
     * @summary Retrieves conversion rates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RatesApiGenerated
     */
    public getConversionRates(options?: AxiosRequestConfig) {
        return RatesApiFp(this.configuration).getConversionRates(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current rates
     * @summary Get current rates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RatesApiGenerated
     */
    public getCurrentRates(options?: AxiosRequestConfig) {
        return RatesApiFp(this.configuration).getCurrentRates(options).then((request) => request(this.axios, this.basePath));
    }
}
