/* tslint:disable */
/* eslint-disable */
/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { VoucherFeeGetFeeResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * VoucherFeeApi - axios parameter creator
 * @export
 */
export const VoucherFeeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves fee for a given voucher amount and currency.
         * @summary Retrieves conversion rates
         * @param {number} amount Voucher amount
         * @param {'NGN' | 'USD'} currency Voucher currency
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFee: async (amount: number, currency: 'NGN' | 'USD', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'amount' is not null or undefined
            assertParamExists('getFee', 'amount', amount)
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('getFee', 'currency', currency)
            const localVarPath = `/v1/voucher-fee`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            if (amount !== undefined) {
                localVarQueryParameter['amount'] = amount;
            }

            if (currency !== undefined) {
                localVarQueryParameter['currency'] = currency;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/voucher-fee',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VoucherFeeApi - functional programming interface
 * @export
 */
export const VoucherFeeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VoucherFeeApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves fee for a given voucher amount and currency.
         * @summary Retrieves conversion rates
         * @param {VoucherFeeApiGetFeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFee(requestParameters: VoucherFeeApiGetFeeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VoucherFeeGetFeeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFee(requestParameters.amount, requestParameters.currency, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * VoucherFeeApi - factory interface
 * @export
 */
export const VoucherFeeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VoucherFeeApiFp(configuration)
    return {
        /**
         * Retrieves fee for a given voucher amount and currency.
         * @summary Retrieves conversion rates
         * @param {VoucherFeeApiGetFeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFee(requestParameters: VoucherFeeApiGetFeeRequest, options?: AxiosRequestConfig): AxiosPromise<VoucherFeeGetFeeResponse> {
            return localVarFp.getFee(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getFee operation in VoucherFeeApi.
 * @export
 * @interface VoucherFeeApiGetFeeRequest
 */
export type VoucherFeeApiGetFeeRequest = {
    
    /**
    * Voucher amount
    * @type {number}
    * @memberof VoucherFeeApiGetFee
    */
    readonly amount: number
    
    /**
    * Voucher currency
    * @type {'NGN' | 'USD'}
    * @memberof VoucherFeeApiGetFee
    */
    readonly currency: 'NGN' | 'USD'
    
}

/**
 * VoucherFeeApiGenerated - object-oriented interface
 * @export
 * @class VoucherFeeApiGenerated
 * @extends {BaseAPI}
 */
export class VoucherFeeApiGenerated extends BaseAPI {
    /**
     * Retrieves fee for a given voucher amount and currency.
     * @summary Retrieves conversion rates
     * @param {VoucherFeeApiGetFeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoucherFeeApiGenerated
     */
    public getFee(requestParameters: VoucherFeeApiGetFeeRequest, options?: AxiosRequestConfig) {
        return VoucherFeeApiFp(this.configuration).getFee(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
