/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiKeyGenerateNewApiKeyResponseData } from './api-key-generate-new-api-key-response-data';

/**
 * 
 * @export
 * @interface ApiKeyGenerateNewApiKeyResponse
 */
export interface ApiKeyGenerateNewApiKeyResponse {
    /**
     * 
     * @type {ApiKeyGenerateNewApiKeyResponseData}
     * @memberof ApiKeyGenerateNewApiKeyResponse
     */
    'data'?: ApiKeyGenerateNewApiKeyResponseData;
}

