/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BalanceGetAccountBalanceResponseData } from './balance-get-account-balance-response-data';

/**
 * 
 * @export
 * @interface BalanceGetAccountBalanceResponse
 */
export interface BalanceGetAccountBalanceResponse {
    /**
     * 
     * @type {BalanceGetAccountBalanceResponseData}
     * @memberof BalanceGetAccountBalanceResponse
     */
    'data'?: BalanceGetAccountBalanceResponseData;
    /**
     * 
     * @type {string}
     * @memberof BalanceGetAccountBalanceResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BalanceGetAccountBalanceResponse
     */
    'success'?: BalanceGetAccountBalanceResponseSuccessEnum;
}

type BalanceGetAccountBalanceResponseSuccessEnum = true


