/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BalanceGetAccountBalanceResponseData
 */
export interface BalanceGetAccountBalanceResponseData {
    /**
     * Merchant\'s balance amount
     * @type {number}
     * @memberof BalanceGetAccountBalanceResponseData
     */
    'amount'?: number;
    /**
     * The currency passed by merchant
     * @type {string}
     * @memberof BalanceGetAccountBalanceResponseData
     */
    'currency'?: string;
    /**
     * Merchant\'susername
     * @type {string}
     * @memberof BalanceGetAccountBalanceResponseData
     */
    'merchant'?: string;
    /**
     * Total count of voucher redeemption for a given merchant
     * @type {number}
     * @memberof BalanceGetAccountBalanceResponseData
     */
    'txnCount'?: number;
}

