/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BalanceGetAccountBalance200ResponseData } from './balance-get-account-balance200-response-data';

/**
 * 
 * @export
 * @interface BalanceGetAccountBalance200Response
 */
export interface BalanceGetAccountBalance200Response {
    /**
     * 
     * @type {BalanceGetAccountBalance200ResponseData}
     * @memberof BalanceGetAccountBalance200Response
     */
    'data'?: BalanceGetAccountBalance200ResponseData;
    /**
     * 
     * @type {string}
     * @memberof BalanceGetAccountBalance200Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BalanceGetAccountBalance200Response
     */
    'success'?: boolean;
}

