/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BalanceGetAccountBalance200ResponseDataBalances } from './balance-get-account-balance200-response-data-balances';

/**
 * 
 * @export
 * @interface BalanceGetAccountBalance200ResponseData
 */
export interface BalanceGetAccountBalance200ResponseData {
    /**
     * 
     * @type {BalanceGetAccountBalance200ResponseDataBalances}
     * @memberof BalanceGetAccountBalance200ResponseData
     */
    'balances'?: BalanceGetAccountBalance200ResponseDataBalances;
}

