/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BalanceTransferFundsResponseData
 */
export interface BalanceTransferFundsResponseData {
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'fromCurrency'?: BalanceTransferFundsResponseDataFromCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'receiveAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'sender'?: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'senderPrevbalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'status'?: BalanceTransferFundsResponseDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'toCurrency'?: BalanceTransferFundsResponseDataToCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponseData
     */
    'username'?: string;
}

type BalanceTransferFundsResponseDataFromCurrencyEnum = 'NGN' | 'USD'
type BalanceTransferFundsResponseDataStatusEnum = 'fullfiled' | 'processing' | 'failed'
type BalanceTransferFundsResponseDataToCurrencyEnum = 'NGN' | 'USD'


