/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BalanceGetAccountBalance200ResponseDataBalances
 */
export interface BalanceGetAccountBalance200ResponseDataBalances {
    /**
     * User\'s balance amount
     * @type {number}
     * @memberof BalanceGetAccountBalance200ResponseDataBalances
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof BalanceGetAccountBalance200ResponseDataBalances
     */
    'formattedAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof BalanceGetAccountBalance200ResponseDataBalances
     */
    'toCurrency'?: string;
    /**
     * 
     * @type {number}
     * @memberof BalanceGetAccountBalance200ResponseDataBalances
     */
    'totalRecieved'?: number;
    /**
     * 
     * @type {number}
     * @memberof BalanceGetAccountBalance200ResponseDataBalances
     */
    'totalSent'?: number;
    /**
     * 
     * @type {number}
     * @memberof BalanceGetAccountBalance200ResponseDataBalances
     */
    'txnCount'?: number;
}

