/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BalanceTransferFundsResponseData } from './balance-transfer-funds-response-data';

/**
 * 
 * @export
 * @interface BalanceTransferFundsResponse
 */
export interface BalanceTransferFundsResponse {
    /**
     * 
     * @type {BalanceTransferFundsResponseData}
     * @memberof BalanceTransferFundsResponse
     */
    'data'?: BalanceTransferFundsResponseData;
    /**
     * 
     * @type {string}
     * @memberof BalanceTransferFundsResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BalanceTransferFundsResponse
     */
    'success'?: boolean;
}

