/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BankAccountVerifyAndReturnDetailsResponseData
 */
export interface BankAccountVerifyAndReturnDetailsResponseData {
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'accountname'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'accountnumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'deleted_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'internalreference'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'is_trashed'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'is_visible'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'phonenumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'responsecode'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'responsemessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'uniquereference'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsResponseData
     */
    'updated_at'?: string;
}

