/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BankGetSupportedBanksResponseDataInner
 */
export interface BankGetSupportedBanksResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof BankGetSupportedBanksResponseDataInner
     */
    'Code'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankGetSupportedBanksResponseDataInner
     */
    'Name'?: string;
}

