/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankGetSupportedBanksResponseDataInner } from './bank-get-supported-banks-response-data-inner';

/**
 * 
 * @export
 * @interface BankGetSupportedBanksResponse
 */
export interface BankGetSupportedBanksResponse {
    /**
     * 
     * @type {Array<BankGetSupportedBanksResponseDataInner>}
     * @memberof BankGetSupportedBanksResponse
     */
    'data'?: Array<BankGetSupportedBanksResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof BankGetSupportedBanksResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BankGetSupportedBanksResponse
     */
    'success'?: boolean;
}

