/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankAccountVerifyAndReturnDetailsResponseData } from './bank-account-verify-and-return-details-response-data';

/**
 * 
 * @export
 * @interface BankAccountVerifyAndReturnDetailsResponse
 */
export interface BankAccountVerifyAndReturnDetailsResponse {
    /**
     * 
     * @type {BankAccountVerifyAndReturnDetailsResponseData}
     * @memberof BankAccountVerifyAndReturnDetailsResponse
     */
    'data'?: BankAccountVerifyAndReturnDetailsResponseData;
}

