/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BankAccountVerifyAndReturnDetailsRequest
 */
export interface BankAccountVerifyAndReturnDetailsRequest {
    /**
     * The account number.
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsRequest
     */
    'accountNumber': string;
    /**
     * The bank code.
     * @type {string}
     * @memberof BankAccountVerifyAndReturnDetailsRequest
     */
    'bankCode': string;
}

