/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyListSupportedCurrenciesResponseData } from './currency-list-supported-currencies-response-data';

/**
 * 
 * @export
 * @interface CurrencyListSupportedCurrenciesResponse
 */
export interface CurrencyListSupportedCurrenciesResponse {
    /**
     * 
     * @type {CurrencyListSupportedCurrenciesResponseData}
     * @memberof CurrencyListSupportedCurrenciesResponse
     */
    'data'?: CurrencyListSupportedCurrenciesResponseData;
}

