/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantsGetRecordResponseData } from './merchants-get-record-response-data';

/**
 * 
 * @export
 * @interface MerchantsGetRecordResponse
 */
export interface MerchantsGetRecordResponse {
    /**
     * 
     * @type {MerchantsGetRecordResponseData}
     * @memberof MerchantsGetRecordResponse
     */
    'data'?: MerchantsGetRecordResponseData;
    /**
     * 
     * @type {string}
     * @memberof MerchantsGetRecordResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantsGetRecordResponse
     */
    'success'?: MerchantsGetRecordResponseSuccessEnum;
}

type MerchantsGetRecordResponseSuccessEnum = true


