/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantsGetRecordResponseData
 */
export interface MerchantsGetRecordResponseData {
    /**
     * Merchant\'s credit currency
     * @type {string}
     * @memberof MerchantsGetRecordResponseData
     */
    'creditCurrency'?: MerchantsGetRecordResponseDataCreditCurrencyEnum;
    /**
     * Merchant email address
     * @type {string}
     * @memberof MerchantsGetRecordResponseData
     */
    'email'?: string;
    /**
     * API key expiry date and time
     * @type {string}
     * @memberof MerchantsGetRecordResponseData
     */
    'expires'?: string;
    /**
     * Merchant logo URL
     * @type {string}
     * @memberof MerchantsGetRecordResponseData
     */
    'logo'?: string;
    /**
     * Merchant username
     * @type {string}
     * @memberof MerchantsGetRecordResponseData
     */
    'username'?: string;
}

type MerchantsGetRecordResponseDataCreditCurrencyEnum = 'NGN' | 'USD'


