/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantsUpdateRecordResponseData } from './merchants-update-record-response-data';

/**
 * 
 * @export
 * @interface MerchantsUpdateRecordResponse
 */
export interface MerchantsUpdateRecordResponse {
    /**
     * 
     * @type {MerchantsUpdateRecordResponseData}
     * @memberof MerchantsUpdateRecordResponse
     */
    'data'?: MerchantsUpdateRecordResponseData;
    /**
     * 
     * @type {string}
     * @memberof MerchantsUpdateRecordResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantsUpdateRecordResponse
     */
    'success'?: MerchantsUpdateRecordResponseSuccessEnum;
}

type MerchantsUpdateRecordResponseSuccessEnum = true


