/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantsUpdateRecordRequest
 */
export interface MerchantsUpdateRecordRequest {
    /**
     * Merchant callback URL. Webhook will be sent to this URL.
     * @type {string}
     * @memberof MerchantsUpdateRecordRequest
     */
    'callbackUrl'?: string;
    /**
     * Merchants can set this property to their desired currency. Their balance on Ventogram will be credited with this currency when their users redeem voucher created on Ventogram. Conversion between different currencies will be performed at the rate which is obtainable at the time of redeeming the voucher. If this is not set by the merchant,  their balance will be credited with the currency used in creating the voucher.
     * @type {string}
     * @memberof MerchantsUpdateRecordRequest
     */
    'creditCurrency'?: MerchantsUpdateRecordRequestCreditCurrencyEnum;
    /**
     * Bearer of the voucher fee
     * @type {string}
     * @memberof MerchantsUpdateRecordRequest
     */
    'feeBearer'?: MerchantsUpdateRecordRequestFeeBearerEnum;
    /**
     * Merchant logo URL
     * @type {string}
     * @memberof MerchantsUpdateRecordRequest
     */
    'logo'?: string;
}

type MerchantsUpdateRecordRequestCreditCurrencyEnum = 'NGN' | 'USD' | ''
type MerchantsUpdateRecordRequestFeeBearerEnum = 'client' | 'merchant'


