/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantsUpdateRecordResponseData
 */
export interface MerchantsUpdateRecordResponseData {
    /**
     * 
     * @type {string}
     * @memberof MerchantsUpdateRecordResponseData
     */
    'callbackUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantsUpdateRecordResponseData
     */
    'creditCurrency'?: MerchantsUpdateRecordResponseDataCreditCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof MerchantsUpdateRecordResponseData
     */
    'feeBearer'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantsUpdateRecordResponseData
     */
    'logo'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantsUpdateRecordResponseData
     */
    'username'?: string;
}

type MerchantsUpdateRecordResponseDataCreditCurrencyEnum = 'NGN' | 'USD'


