/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MockPaymentRequestSubmissionRequest
 */
export interface MockPaymentRequestSubmissionRequest {
    /**
     * Amount to pay. This can be used to simulate overpayment and underpayment in staging environment. If this field is not provided, the expected amount will be paid.
     * @type {number}
     * @memberof MockPaymentRequestSubmissionRequest
     */
    'amount'?: number;
    /**
     * ID of the voucher to be paid
     * @type {string}
     * @memberof MockPaymentRequestSubmissionRequest
     */
    'voucherId': string;
}

