/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MockPaymentRequestSubmission400Response
 */
export interface MockPaymentRequestSubmission400Response {
    /**
     * 
     * @type {string}
     * @memberof MockPaymentRequestSubmission400Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MockPaymentRequestSubmission400Response
     */
    'success'?: MockPaymentRequestSubmission400ResponseSuccessEnum;
}

type MockPaymentRequestSubmission400ResponseSuccessEnum = false


