/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentResolveOverpaidTransactionResponse
 */
export interface PaymentResolveOverpaidTransactionResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentResolveOverpaidTransactionResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentResolveOverpaidTransactionResponse
     */
    'success'?: boolean;
}

