/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentCreateNewPaymentResponseData } from './payment-create-new-payment-response-data';

/**
 * 
 * @export
 * @interface PaymentCreateNewPaymentResponse
 */
export interface PaymentCreateNewPaymentResponse {
    /**
     * 
     * @type {PaymentCreateNewPaymentResponseData}
     * @memberof PaymentCreateNewPaymentResponse
     */
    'data'?: PaymentCreateNewPaymentResponseData;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentCreateNewPaymentResponse
     */
    'success'?: boolean;
}

