/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentCreateNewPaymentResponseData
 */
export interface PaymentCreateNewPaymentResponseData {
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    '_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'businessId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'confirmedAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'customerEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'expTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'incomingAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'incomingCurrency'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'outgoingAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'outgoingCurrency'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'paymentType'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'senderUsername'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'threadTS'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'unconfirmedAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateNewPaymentResponseData
     */
    'updatedAt'?: string;
}

