/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentCreateNewPaymentRequest
 */
export interface PaymentCreateNewPaymentRequest {
    /**
     * The account name. Required when paymentType is bank
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'accountName'?: string;
    /**
     * The account number. Required when paymentType is bank
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'accountNumber'?: string;
    /**
     * The bank name. Required when paymentType is bank
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'bank'?: string;
    /**
     * The bank code. Required when paymentType is bank
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'bankCode'?: string;
    /**
     * The business id
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'businessId': string;
    /**
     * The coinprofile username. Required when paymentType is profile
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'coinprofileUsername'?: string;
    /**
     * The country. Required when paymentType is bank
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'country'?: string;
    /**
     * The rate key
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'customerEmail': string;
    /**
     * The incoming amount
     * @type {number}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'incomingAmount'?: number;
    /**
     * The incoming currency
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'incomingCurrency': string;
    /**
     * The outgoing amount
     * @type {number}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'outgoingAmount'?: number;
    /**
     * The outgoing currency
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'outgoingCurrency': string;
    /**
     * The payment type
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'paymentType': string;
    /**
     * The rate key
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'rateKey'?: string;
    /**
     * The reference
     * @type {string}
     * @memberof PaymentCreateNewPaymentRequest
     */
    'reference'?: string;
}

