/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RatesGetConversionRatesResponseDataUSDNGN } from './rates-get-conversion-rates-response-data-usdngn';

/**
 * 
 * @export
 * @interface RatesGetConversionRatesResponseData
 */
export interface RatesGetConversionRatesResponseData {
    /**
     * 
     * @type {RatesGetConversionRatesResponseDataUSDNGN}
     * @memberof RatesGetConversionRatesResponseData
     */
    'USDNGN'?: RatesGetConversionRatesResponseDataUSDNGN;
}

