/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RatesGetCurrentRatesResponseData } from './rates-get-current-rates-response-data';

/**
 * 
 * @export
 * @interface RatesGetCurrentRatesResponse
 */
export interface RatesGetCurrentRatesResponse {
    /**
     * 
     * @type {RatesGetCurrentRatesResponseData}
     * @memberof RatesGetCurrentRatesResponse
     */
    'data'?: RatesGetCurrentRatesResponseData;
}

