/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RatesGetConversionRatesResponseDataUSDNGN
 */
export interface RatesGetConversionRatesResponseDataUSDNGN {
    /**
     * description text
     * @type {string}
     * @memberof RatesGetConversionRatesResponseDataUSDNGN
     */
    'description'?: string;
    /**
     * Ventogram signed rate key
     * @type {string}
     * @memberof RatesGetConversionRatesResponseDataUSDNGN
     */
    'rateKey'?: string;
    /**
     * 1 USD is equal to 500 NGN in this example
     * @type {number}
     * @memberof RatesGetConversionRatesResponseDataUSDNGN
     */
    'value'?: number;
}

