/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RatesGetCurrentRatesResponseDataYOURCURRENCY } from './rates-get-current-rates-response-data-yourcurrency';

/**
 * 
 * @export
 * @interface RatesGetCurrentRatesResponseData
 */
export interface RatesGetCurrentRatesResponseData {
    /**
     * 
     * @type {RatesGetCurrentRatesResponseDataYOURCURRENCY}
     * @memberof RatesGetCurrentRatesResponseData
     */
    'YOUR_CURRENCY'?: RatesGetCurrentRatesResponseDataYOURCURRENCY;
    /**
     * 
     * @type {string}
     * @memberof RatesGetCurrentRatesResponseData
     */
    'publicKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof RatesGetCurrentRatesResponseData
     */
    'signature'?: string;
}

