/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RatesGetConversionRatesResponseData } from './rates-get-conversion-rates-response-data';

/**
 * 
 * @export
 * @interface RatesGetConversionRatesResponse
 */
export interface RatesGetConversionRatesResponse {
    /**
     * 
     * @type {RatesGetConversionRatesResponseData}
     * @memberof RatesGetConversionRatesResponse
     */
    'data'?: RatesGetConversionRatesResponseData;
    /**
     * 
     * @type {string}
     * @memberof RatesGetConversionRatesResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RatesGetConversionRatesResponse
     */
    'success'?: RatesGetConversionRatesResponseSuccessEnum;
}

type RatesGetConversionRatesResponseSuccessEnum = true


