/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RatesGetCurrentRatesResponseDataYOURCURRENCY
 */
export interface RatesGetCurrentRatesResponseDataYOURCURRENCY {
    /**
     * 
     * @type {string}
     * @memberof RatesGetCurrentRatesResponseDataYOURCURRENCY
     */
    'key'?: string;
    /**
     * 
     * @type {number}
     * @memberof RatesGetCurrentRatesResponseDataYOURCURRENCY
     */
    'rate'?: number;
}

