/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionGetUserTransactionSummaryResponseDataSummary
 */
export interface TransactionGetUserTransactionSummaryResponseDataSummary {
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionSummaryResponseDataSummary
     */
    'duration'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionSummaryResponseDataSummary
     */
    'txnCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionSummaryResponseDataSummary
     */
    'volume'?: number;
}

