/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionsGetMerchantTransactionSummaryResponseData
 */
export interface TransactionsGetMerchantTransactionSummaryResponseData {
    /**
     * Total count of paid vouchers
     * @type {number}
     * @memberof TransactionsGetMerchantTransactionSummaryResponseData
     */
    'totalPaid'?: number;
    /**
     * Total count of redeemed vouchers
     * @type {number}
     * @memberof TransactionsGetMerchantTransactionSummaryResponseData
     */
    'totalRedeemed'?: number;
    /**
     * Total count of unpaid vouchers
     * @type {number}
     * @memberof TransactionsGetMerchantTransactionSummaryResponseData
     */
    'totalUnpaid'?: number;
    /**
     * Total count of unredeemed vouchers
     * @type {number}
     * @memberof TransactionsGetMerchantTransactionSummaryResponseData
     */
    'totalUnredeemed'?: number;
}

