/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionGetUserTransactionSummaryResponseData } from './transaction-get-user-transaction-summary-response-data';

/**
 * 
 * @export
 * @interface TransactionGetUserTransactionSummaryResponse
 */
export interface TransactionGetUserTransactionSummaryResponse {
    /**
     * 
     * @type {TransactionGetUserTransactionSummaryResponseData}
     * @memberof TransactionGetUserTransactionSummaryResponse
     */
    'data'?: TransactionGetUserTransactionSummaryResponseData;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionSummaryResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionGetUserTransactionSummaryResponse
     */
    'success'?: boolean;
}

