/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionsGetMerchantTransactionSummaryResponseData } from './transactions-get-merchant-transaction-summary-response-data';

/**
 * 
 * @export
 * @interface TransactionsGetMerchantTransactionSummaryResponse
 */
export interface TransactionsGetMerchantTransactionSummaryResponse {
    /**
     * 
     * @type {TransactionsGetMerchantTransactionSummaryResponseData}
     * @memberof TransactionsGetMerchantTransactionSummaryResponse
     */
    'data'?: TransactionsGetMerchantTransactionSummaryResponseData;
    /**
     * 
     * @type {string}
     * @memberof TransactionsGetMerchantTransactionSummaryResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionsGetMerchantTransactionSummaryResponse
     */
    'success'?: TransactionsGetMerchantTransactionSummaryResponseSuccessEnum;
}

type TransactionsGetMerchantTransactionSummaryResponseSuccessEnum = true


