/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionGetUserTransactionsResponseDataDataInner
 */
export interface TransactionGetUserTransactionsResponseDataDataInner {
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'version'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'businessId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'date'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'fee'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'fromAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'fromCurrency'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'isFromRegUser'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'prevBalance'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'sender'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'senderPrevbalance'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponseDataDataInner
     */
    'username'?: string;
}

