/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionGetUserTransactionsResponseData } from './transaction-get-user-transactions-response-data';

/**
 * 
 * @export
 * @interface TransactionGetUserTransactionsResponse
 */
export interface TransactionGetUserTransactionsResponse {
    /**
     * 
     * @type {TransactionGetUserTransactionsResponseData}
     * @memberof TransactionGetUserTransactionsResponse
     */
    'data'?: TransactionGetUserTransactionsResponseData;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetUserTransactionsResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionGetUserTransactionsResponse
     */
    'success'?: boolean;
}

