/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionGetUserTransactionsResponseDataDataInner } from './transaction-get-user-transactions-response-data-data-inner';

/**
 * 
 * @export
 * @interface TransactionGetUserTransactionsResponseData
 */
export interface TransactionGetUserTransactionsResponseData {
    /**
     * 
     * @type {Array<TransactionGetUserTransactionsResponseDataDataInner>}
     * @memberof TransactionGetUserTransactionsResponseData
     */
    'data'?: Array<TransactionGetUserTransactionsResponseDataDataInner>;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseData
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseData
     */
    'pages'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseData
     */
    'perPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetUserTransactionsResponseData
     */
    'total'?: number;
}

