/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionGetUserTransactionSummaryResponseDataSummary } from './transaction-get-user-transaction-summary-response-data-summary';
import { TransactionGetUserTransactionsResponseData } from './transaction-get-user-transactions-response-data';

/**
 * 
 * @export
 * @interface TransactionGetUserTransactionSummaryResponseData
 */
export interface TransactionGetUserTransactionSummaryResponseData {
    /**
     * 
     * @type {TransactionGetUserTransactionSummaryResponseDataSummary}
     * @memberof TransactionGetUserTransactionSummaryResponseData
     */
    'summary'?: TransactionGetUserTransactionSummaryResponseDataSummary;
    /**
     * 
     * @type {TransactionGetUserTransactionsResponseData}
     * @memberof TransactionGetUserTransactionSummaryResponseData
     */
    'txn'?: TransactionGetUserTransactionsResponseData;
}

