/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionGetDetailsResponse
 */
export interface TransactionGetDetailsResponse {
    /**
     * 
     * @type {number}
     * @memberof TransactionGetDetailsResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'businessId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetDetailsResponse
     */
    'fromAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'fromCurrency'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionGetDetailsResponse
     */
    'isFromRegUser'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'memo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionGetDetailsResponse
     */
    'prevBalance'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'sender'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'status'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionGetDetailsResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionGetDetailsResponse
     */
    'username'?: string;
}

