/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherGetMultipleRecordsResponseDataInner
 */
export interface VoucherGetMultipleRecordsResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'currency'?: string;
    /**
     * This is defined only if the voucher payment has been received
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'dateRedeemed'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'expectedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'fee'?: number;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'feeBearer'?: VoucherGetMultipleRecordsResponseDataInnerFeeBearerEnum;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'fullname'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'memo'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'merchant'?: string;
    /**
     * This is defined only if the voucher payment has been received
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'paidAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'paymentStatus'?: VoucherGetMultipleRecordsResponseDataInnerPaymentStatusEnum;
    /**
     * This is defined only if the voucher has been paid and redeemed
     * @type {number}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'rate'?: number;
    /**
     * This is defined only if the voucher was created using a valid rate key
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'rateKey'?: string;
    /**
     * This is defined only if the voucher payment has been received
     * @type {number}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'receivedAmount'?: number;
    /**
     * This is defined only if the voucher payment has been received
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseDataInner
     */
    'voucherCode'?: string;
}

type VoucherGetMultipleRecordsResponseDataInnerFeeBearerEnum = 'client' | 'merchant'
type VoucherGetMultipleRecordsResponseDataInnerPaymentStatusEnum = 'paid' | 'unpaid'


