/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherFeeGetFeeResponseData } from './voucher-fee-get-fee-response-data';

/**
 * 
 * @export
 * @interface VoucherFeeGetFeeResponse
 */
export interface VoucherFeeGetFeeResponse {
    /**
     * 
     * @type {VoucherFeeGetFeeResponseData}
     * @memberof VoucherFeeGetFeeResponse
     */
    'data'?: VoucherFeeGetFeeResponseData;
    /**
     * 
     * @type {string}
     * @memberof VoucherFeeGetFeeResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherFeeGetFeeResponse
     */
    'success'?: VoucherFeeGetFeeResponseSuccessEnum;
}

type VoucherFeeGetFeeResponseSuccessEnum = true


