/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherCreatePaymentResponseData
 */
export interface VoucherCreatePaymentResponseData {
    /**
     * Voucher unique id
     * @type {string}
     * @memberof VoucherCreatePaymentResponseData
     */
    'id'?: string;
}

