/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherCreatePayment400Response
 */
export interface VoucherCreatePayment400Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof VoucherCreatePayment400Response
     */
    'errors'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof VoucherCreatePayment400Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherCreatePayment400Response
     */
    'success'?: VoucherCreatePayment400ResponseSuccessEnum;
}

type VoucherCreatePayment400ResponseSuccessEnum = false


