/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherRedeemExistingUnusedRequest
 */
export interface VoucherRedeemExistingUnusedRequest {
    /**
     * Email that was used to create the voucher
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedRequest
     */
    'email': string;
    /**
     * Voucher code to be redeemed
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedRequest
     */
    'voucherCode': string;
}

