/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherGetRecordResponseDataInner
 */
export interface VoucherGetRecordResponseDataInner {
    /**
     * Type of created bank account. Note that this property is only available in v2.
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'accountType'?: VoucherGetRecordResponseDataInnerAccountTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'amount'?: number;
    /**
     * This property is optional. Only available if the voucher has been cancelled.
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'cancelledAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'currency'?: string;
    /**
     * Timestamp of when the voucher was redeemed. If voucher has not been redeemed, this field is undefined.
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'dateRedeemed'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'fee'?: number;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'feeBearer'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'fullname'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'memo'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'merchant'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'paymentExpiresAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'paymentStatus'?: VoucherGetRecordResponseDataInnerPaymentStatusEnum;
    /**
     * Voucher code. Present only if voucher has been paid
     * @type {string}
     * @memberof VoucherGetRecordResponseDataInner
     */
    'voucherCode'?: string;
}

type VoucherGetRecordResponseDataInnerAccountTypeEnum = 'dynamic' | 'static'
type VoucherGetRecordResponseDataInnerPaymentStatusEnum = 'paid' | 'unpaid' | 'declined'


