/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherRedeemAndWithdrawResponseData } from './voucher-redeem-and-withdraw-response-data';

/**
 * 
 * @export
 * @interface VoucherRedeemAndWithdrawResponse
 */
export interface VoucherRedeemAndWithdrawResponse {
    /**
     * 
     * @type {VoucherRedeemAndWithdrawResponseData}
     * @memberof VoucherRedeemAndWithdrawResponse
     */
    'data'?: VoucherRedeemAndWithdrawResponseData;
    /**
     * 
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherRedeemAndWithdrawResponse
     */
    'success'?: VoucherRedeemAndWithdrawResponseSuccessEnum;
}

type VoucherRedeemAndWithdrawResponseSuccessEnum = true


