/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherGetMultipleRecordsResponseDataInner } from './voucher-get-multiple-records-response-data-inner';
import { VoucherGetMultipleRecordsResponseMeta } from './voucher-get-multiple-records-response-meta';

/**
 * 
 * @export
 * @interface VoucherGetMultipleRecordsResponse
 */
export interface VoucherGetMultipleRecordsResponse {
    /**
     * An array containing the retrieved voucher records, sorted in descending order by their creation date.
     * @type {Array<VoucherGetMultipleRecordsResponseDataInner>}
     * @memberof VoucherGetMultipleRecordsResponse
     */
    'data'?: Array<VoucherGetMultipleRecordsResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponse
     */
    'message'?: string;
    /**
     * 
     * @type {VoucherGetMultipleRecordsResponseMeta}
     * @memberof VoucherGetMultipleRecordsResponse
     */
    'meta'?: VoucherGetMultipleRecordsResponseMeta;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherGetMultipleRecordsResponse
     */
    'success'?: VoucherGetMultipleRecordsResponseSuccessEnum;
}

type VoucherGetMultipleRecordsResponseSuccessEnum = true


