/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherRedeemAndWithdrawResponseData
 */
export interface VoucherRedeemAndWithdrawResponseData {
    /**
     * Voucher fee in the outgoing currency
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'convertedVoucherFee'?: number;
    /**
     * The same as toCurrency
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'convertedVoucherFeeCurrency'?: string;
    /**
     * Merchant\'s balance currency
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'creditCurrency'?: string;
    /**
     * Merchant\'s balance after redeeming voucher
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'currentBalance'?: number;
    /**
     * Email that aws used to create the voucher
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'email'?: string;
    /**
     * The bearer of voucher fee
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'feeBearer'?: VoucherRedeemAndWithdrawResponseDataFeeBearerEnum;
    /**
     * Voucher payment amount.
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'fromAmount'?: number;
    /**
     * voucher payment currency
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'fromCurrency'?: string;
    /**
     * Voucher ID
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'id'?: string;
    /**
     * username of the merchant that created the voucher
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'merchant'?: string;
    /**
     * This can be optionally provided by the merchant in the request if they want some of the received amount to be added to their Ventogram balance.
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'merchantFee'?: number;
    /**
     * Merchant\'s balance before redeeming voucher
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'previousBalance'?: number;
    /**
     * The exchange rate that was used for conversion (if applicable) at the time of redeeming the voucher. If there\'s no conversion, the value is 1.
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'rate'?: number;
    /**
     * This is basically a unique id
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'reference'?: string;
    /**
     * The crypto wallet address to which asset was transferred
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'toAccount'?: string;
    /**
     * The amount that was sent to user wallet address.
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'toAmount'?: number;
    /**
     * The currency that was sent to user wallet.
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'toCurrency'?: string;
    /**
     * Voucher code to be redeemed
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'voucherCode'?: string;
    /**
     * The fee associated with voucher in the payment currency. This will be deducted from merchant\'s balance if merchant is the fee bearer.
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'voucherFee'?: number;
    /**
     * The processing fee for the crypto transfer that will be deducted from the merchant\'s account. Merchants must maintain a sufficient balance to utilize the redeem-and-withdraw endpoint.
     * @type {number}
     * @memberof VoucherRedeemAndWithdrawResponseData
     */
    'withdrawalFee'?: number;
}

type VoucherRedeemAndWithdrawResponseDataFeeBearerEnum = 'merchant' | 'client'


