/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherMinmaxAmountGetMinMaxAmountResponseData } from './voucher-minmax-amount-get-min-max-amount-response-data';

/**
 * 
 * @export
 * @interface VoucherMinmaxAmountGetMinMaxAmountResponse
 */
export interface VoucherMinmaxAmountGetMinMaxAmountResponse {
    /**
     * 
     * @type {VoucherMinmaxAmountGetMinMaxAmountResponseData}
     * @memberof VoucherMinmaxAmountGetMinMaxAmountResponse
     */
    'data'?: VoucherMinmaxAmountGetMinMaxAmountResponseData;
    /**
     * 
     * @type {string}
     * @memberof VoucherMinmaxAmountGetMinMaxAmountResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherMinmaxAmountGetMinMaxAmountResponse
     */
    'success'?: VoucherMinmaxAmountGetMinMaxAmountResponseSuccessEnum;
}

type VoucherMinmaxAmountGetMinMaxAmountResponseSuccessEnum = true


