/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherGetMultipleRecordsResponseMeta
 */
export interface VoucherGetMultipleRecordsResponseMeta {
    /**
     * Contanis the URL of the next page to be fetched relative on the URL parameters of the last paged fetched. This is null if there are no more records to fetch.
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseMeta
     */
    'nextPage'?: string;
    /**
     * Contanis the URL of the previous page that was fetched fetched relative on the URL parameters of the current paged
     * @type {string}
     * @memberof VoucherGetMultipleRecordsResponseMeta
     */
    'prevPage'?: string;
}

