/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN } from './voucher-minmax-amount-get-min-max-amount-response-data-ngn';
import { VoucherMinmaxAmountGetMinMaxAmountResponseDataUSD } from './voucher-minmax-amount-get-min-max-amount-response-data-usd';

/**
 * 
 * @export
 * @interface VoucherMinmaxAmountGetMinMaxAmountResponseData
 */
export interface VoucherMinmaxAmountGetMinMaxAmountResponseData {
    /**
     * 
     * @type {VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN}
     * @memberof VoucherMinmaxAmountGetMinMaxAmountResponseData
     */
    'NGN'?: VoucherMinmaxAmountGetMinMaxAmountResponseDataNGN;
    /**
     * 
     * @type {VoucherMinmaxAmountGetMinMaxAmountResponseDataUSD}
     * @memberof VoucherMinmaxAmountGetMinMaxAmountResponseData
     */
    'USD'?: VoucherMinmaxAmountGetMinMaxAmountResponseDataUSD;
}

