/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherCreatePaymentResponseData } from './voucher-create-payment-response-data';

/**
 * 
 * @export
 * @interface VoucherCreatePaymentResponse
 */
export interface VoucherCreatePaymentResponse {
    /**
     * 
     * @type {VoucherCreatePaymentResponseData}
     * @memberof VoucherCreatePaymentResponse
     */
    'data'?: VoucherCreatePaymentResponseData;
    /**
     * 
     * @type {string}
     * @memberof VoucherCreatePaymentResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherCreatePaymentResponse
     */
    'success'?: VoucherCreatePaymentResponseSuccessEnum;
}

type VoucherCreatePaymentResponseSuccessEnum = true


