/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherRedeemAndWithdraw400Response
 */
export interface VoucherRedeemAndWithdraw400Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof VoucherRedeemAndWithdraw400Response
     */
    'errors'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof VoucherRedeemAndWithdraw400Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherRedeemAndWithdraw400Response
     */
    'success'?: VoucherRedeemAndWithdraw400ResponseSuccessEnum;
}

type VoucherRedeemAndWithdraw400ResponseSuccessEnum = false


