/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherGetRecord404Response
 */
export interface VoucherGetRecord404Response {
    /**
     * 
     * @type {Array<any>}
     * @memberof VoucherGetRecord404Response
     */
    'errors'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecord404Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherGetRecord404Response
     */
    'success'?: VoucherGetRecord404ResponseSuccessEnum;
}

type VoucherGetRecord404ResponseSuccessEnum = false


