/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoucherGetRecordResponseDataInner } from './voucher-get-record-response-data-inner';

/**
 * 
 * @export
 * @interface VoucherGetRecordResponse
 */
export interface VoucherGetRecordResponse {
    /**
     * 
     * @type {Array<VoucherGetRecordResponseDataInner>}
     * @memberof VoucherGetRecordResponse
     */
    'data'?: Array<VoucherGetRecordResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof VoucherGetRecordResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherGetRecordResponse
     */
    'success'?: VoucherGetRecordResponseSuccessEnum;
}

type VoucherGetRecordResponseSuccessEnum = true


