/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherRedeemAndWithdrawRequest
 */
export interface VoucherRedeemAndWithdrawRequest {
    /**
     * Must be provided along with newtwork. The crypto wallet address on the provided network, to which crypto equivalent will be sent
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'cryptoAddress': string;
    /**
     * Cryptocurrency to send to the provided wallet details
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'currency': VoucherRedeemAndWithdrawRequestCurrencyEnum;
    /**
     * Email that was used to create the voucher
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'email': string;
    /**
     * In USD (optional) with a precision of 2 decimal places (max). Can be supplied if the merchant want to withdraw a portion of the voucher amount into their Ventogram balance. This must be a fraction or all of voucher value (ie received amount - voucher fee)
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'merchantFee'?: string;
    /**
     * Supported crypto network
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'network': string;
    /**
     * This is a Ventogram-signed rate key. This will be returned in response if the signed rate was used for conversion.
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'rateKey'?: string;
    /**
     * Voucher code to be redeemed
     * @type {string}
     * @memberof VoucherRedeemAndWithdrawRequest
     */
    'voucherCode': string;
}

type VoucherRedeemAndWithdrawRequestCurrencyEnum = 'USDC' | 'USDT'


