/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoucherRedeemExistingUnusedResponseData
 */
export interface VoucherRedeemExistingUnusedResponseData {
    /**
     * Voucher amount after fee deduction
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'amount'?: number;
    /**
     * voucher payment currency
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'currency'?: VoucherRedeemExistingUnusedResponseDataCurrencyEnum;
    /**
     * Merchant\'s balance after redeeming voucher
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'currentBalance'?: number;
    /**
     * Email that aws used to create the voucher
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'email'?: string;
    /**
     * The fee associated with voucher
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'fee'?: number;
    /**
     * The bearer of voucher fee
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'feeBearer'?: VoucherRedeemExistingUnusedResponseDataFeeBearerEnum;
    /**
     * The amount in the currency that was converted from when conversion was done. If there\'s no conversion, this is the same as toAmount.
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'fromAmount'?: number;
    /**
     * The currency from which conversion was done. If there\'s no conversion, this is the same as toCurrency.
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'fromCurrency'?: string;
    /**
     * Voucher ID
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'id'?: string;
    /**
     * username of the merchant that created the voucher
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'merchant'?: string;
    /**
     * Merchant\'s balance before redeeming voucher
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'previousBalance'?: number;
    /**
     * The exchange rate that was used for conversion when conversion was done. If there\'s no conversion, the value is 1.
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'rate'?: number;
    /**
     * The amount in the currency that was converted to when conversion was done. If there\'s no conversion, this is the same as fromAmount.
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'toAmount'?: number;
    /**
     * The currency to which conversion was done. If there\'s no conversion, this is the same as fromCurrency.
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'toCurrency'?: string;
    /**
     * Voucher code to be redeemed
     * @type {string}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'voucherCode'?: string;
    /**
     * Waved fee (if available)
     * @type {number}
     * @memberof VoucherRedeemExistingUnusedResponseData
     */
    'wavedFee'?: number;
}

type VoucherRedeemExistingUnusedResponseDataCurrencyEnum = 'NGN' | 'USD'
type VoucherRedeemExistingUnusedResponseDataFeeBearerEnum = 'client' | 'merchant'


