/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WalletExecuteTransferResponseDataTransferDetail } from './wallet-execute-transfer-response-data-transfer-detail';

/**
 * 
 * @export
 * @interface WalletExecuteTransferResponseData
 */
export interface WalletExecuteTransferResponseData {
    /**
     * 
     * @type {WalletExecuteTransferResponseDataTransferDetail}
     * @memberof WalletExecuteTransferResponseData
     */
    'transferDetail'?: WalletExecuteTransferResponseDataTransferDetail;
}

