/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WalletExecuteTransferResponseDataTransferDetail
 */
export interface WalletExecuteTransferResponseDataTransferDetail {
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'fromCurrency'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'memo'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'receiveAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'sender'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'toCurrency'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'transactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponseDataTransferDetail
     */
    'username'?: string;
}

