/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WalletGetSupportedConfigResponseData } from './wallet-get-supported-config-response-data';

/**
 * 
 * @export
 * @interface WalletGetSupportedConfigResponse
 */
export interface WalletGetSupportedConfigResponse {
    /**
     * 
     * @type {WalletGetSupportedConfigResponseData}
     * @memberof WalletGetSupportedConfigResponse
     */
    'data'?: WalletGetSupportedConfigResponseData;
    /**
     * 
     * @type {string}
     * @memberof WalletGetSupportedConfigResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WalletGetSupportedConfigResponse
     */
    'state'?: boolean;
}

