/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WalletExecuteTransferRequest
 */
export interface WalletExecuteTransferRequest {
    /**
     * Wallet address to transfer crypto
     * @type {string}
     * @memberof WalletExecuteTransferRequest
     */
    'address': string;
    /**
     * Amount of crypto to be transferred
     * @type {number}
     * @memberof WalletExecuteTransferRequest
     */
    'amount': number;
    /**
     * Currency of the crypto to be transferred
     * @type {string}
     * @memberof WalletExecuteTransferRequest
     */
    'currency': string;
    /**
     * Optional transaction memo
     * @type {string}
     * @memberof WalletExecuteTransferRequest
     */
    'memo'?: string;
    /**
     * Network on which crypto is to be transferred
     * @type {string}
     * @memberof WalletExecuteTransferRequest
     */
    'network': string;
    /**
     * Wallet type
     * @type {string}
     * @memberof WalletExecuteTransferRequest
     */
    'walletType'?: string;
}

