/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WalletExecuteTransferResponseData } from './wallet-execute-transfer-response-data';

/**
 * 
 * @export
 * @interface WalletExecuteTransferResponse
 */
export interface WalletExecuteTransferResponse {
    /**
     * 
     * @type {WalletExecuteTransferResponseData}
     * @memberof WalletExecuteTransferResponse
     */
    'data'?: WalletExecuteTransferResponseData;
    /**
     * 
     * @type {string}
     * @memberof WalletExecuteTransferResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WalletExecuteTransferResponse
     */
    'success'?: boolean;
}

