/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WalletGetAddressesResponseWallet
 */
export interface WalletGetAddressesResponseWallet {
    /**
     * 
     * @type {string}
     * @memberof WalletGetAddressesResponseWallet
     */
    'version'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof WalletGetAddressesResponseWallet
     */
    'addresses'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAddressesResponseWallet
     */
    'appName'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetAddressesResponseWallet
     */
    'createdAt'?: number;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAddressesResponseWallet
     */
    'reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAddressesResponseWallet
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletGetAddressesResponseWallet
     */
    'uid'?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletGetAddressesResponseWallet
     */
    'updatedAt'?: number;
}

