/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WalletGetAddressesResponseWallet } from './wallet-get-addresses-response-wallet';

/**
 * 
 * @export
 * @interface WalletGetAddressesResponse
 */
export interface WalletGetAddressesResponse {
    /**
     * 
     * @type {string}
     * @memberof WalletGetAddressesResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WalletGetAddressesResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletGetAddressesResponseWallet}
     * @memberof WalletGetAddressesResponse
     */
    'wallet'?: WalletGetAddressesResponseWallet;
}

