/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookSubscribeWebhookCallbackRequest
 */
export interface WebhookSubscribeWebhookCallbackRequest {
    /**
     * The callback url. e.g. https://www.example.com/callback
     * @type {string}
     * @memberof WebhookSubscribeWebhookCallbackRequest
     */
    'callbackUrl': string;
}

