/*
Coinprofile business API

Coinprofile business API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookGetCallbackUrlResponseData } from './webhook-get-callback-url-response-data';

/**
 * 
 * @export
 * @interface WebhookGetCallbackUrlResponse
 */
export interface WebhookGetCallbackUrlResponse {
    /**
     * 
     * @type {WebhookGetCallbackUrlResponseData}
     * @memberof WebhookGetCallbackUrlResponse
     */
    'data'?: WebhookGetCallbackUrlResponseData;
    /**
     * 
     * @type {string}
     * @memberof WebhookGetCallbackUrlResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookGetCallbackUrlResponse
     */
    'success'?: boolean;
}

